{% set name = "switcheroo" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/switcheroo-{{ version }}.tar.gz
  sha256: 7963632cd636bb8a70bc3d298d45bd7aff7c11b9bbd55d7336caf9d2fd633557

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }},<4.0

test:
  imports:
    - switcheroo
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/simplistix/switcheroo
  summary: Efficient dispatch-based calling, that might be a switch statement in another language.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - cjw296
